[package]
name = "proto-showbranch"
version = "0.1.0"
authors = ["Yoichi Imai <sunnyone41@gmail.com>"]
build = "build.rs"

[dependencies]
gtk = { version = "0.0.7", features = ["v3_10"] }
libc = "0.2"
gio-sys = "^0"
glib-sys = "^0"
git2 = "0.3"
